import { Client } from "@earendil-works/pi-client";
import {
	applyEvent,
	applyPatch,
	beautifyShellCommand,
	BridgeClient,
	CompactCodec,
	computeCursor,
	computeViewModel,
	DocumentMirror,
	filterPatchForSocket,
	findNextModel,
	InMemoryEntryCacheStore,
	stepWants,
	initFromEntries,
	isLazyFieldPath,
	MAX_IMAGES_PER_MESSAGE,
	MAX_IMAGE_BASE64_LENGTH,
	isModelSelected,
	kindForTool,
	kindFamily,
	leafPathKey,
	leafStreamingKey,
	makeActionIdentity,
	makeActionSummary,
	newestLeafInSubtree,
	planCacheWrites,
	planPull,
	projectCacheEntry,
	projectSnapshot,
	reconcile,
	resolveFieldPath,
	resultPullPaths,
	segmentBlocks,
	sessionAccounting,
	seedDocument,
	setAtPath,
	turnKeyOf,
	validateCursor,
	buildInitialSync,
	computeHistoryTree,
	computeActiveUserPath,
	collapseDrafts,
	computeLaneLayout,
} from "@earendil-works/pi-bridge";
import { createAssistantMessageEventStream, Type } from "@earendil-works/pi-ai";
import { complete, getModel, getProviders, streamSimple } from "@earendil-works/pi-ai/compat";
import { Agent, streamProxy } from "@earendil-works/pi-agent-core";
import { decodeCbor, encodeCbor, PROTOCOL_VERSION } from "@earendil-works/pi-protocol";

// Keep this entry browser-safe. It is bundled by scripts/check-browser-smoke.mjs
// to catch accidental Node-only runtime imports in browser-facing package exports.
const model = getModel("google", "gemini-2.5-flash");
const schema = Type.Object({ prompt: Type.String() });
const stream = createAssistantMessageEventStream();

const agent = new Agent({ initialState: { model }, streamFn: streamSimple });
agent.steer({ role: "user", content: [{ type: "text", text: "queued" }], timestamp: 0 });

console.log(
	model.id,
	getProviders().length,
	typeof complete,
	schema.type,
	typeof stream.push,
	agent.hasQueuedMessages(),
	typeof streamProxy,
	typeof Client,
	PROTOCOL_VERSION,
	decodeCbor(encodeCbor({ browser: true })),
	typeof InstanceInfo,
	typeof BridgeClient,
	typeof CompactCodec,
	typeof applyEvent,
	typeof initFromEntries,
	typeof reconcile,
	typeof computeCursor,
	typeof planCacheWrites,
	typeof projectCacheEntry,
	typeof cacheRecordsOfDocument,
	typeof statusHintOfDocument,
	typeof seedDocument,
	typeof validateCursor,
	typeof buildInitialSync,
	typeof filterPatchForSocket,
	typeof isLazyFieldPath,
	typeof MAX_IMAGES_PER_MESSAGE,
	typeof MAX_IMAGE_BASE64_LENGTH,
	typeof projectSnapshot,
	typeof applyPatch,
	typeof beautifyShellCommand,
	typeof DocumentMirror,
	typeof planPull,
	typeof resolveFieldPath,
	typeof setAtPath,
	typeof computeViewModel,
	typeof findNextModel,
	typeof isModelSelected,
	typeof kindForTool,
	typeof kindFamily,
	typeof stepWants,
	typeof leafPathKey,
	typeof leafStreamingKey,
	typeof makeActionIdentity,
	typeof makeActionSummary,
	typeof newestLeafInSubtree,
	typeof resultPullPaths,
	typeof segmentBlocks,
	typeof sessionAccounting,
	typeof computeHistoryTree,
	typeof computeActiveUserPath,
	typeof collapseDrafts,
	typeof computeLaneLayout,
);
